default_language_version:
    python: python3.8

repos:
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.4.1
    hooks:
      - id: isort
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=131]
